version: '3'
services:
  app:
    env_file: .env
    image: gogs/gogs:${GOGS_VERSION:-latest}
    container_name: gogs
    restart: on-failure
    ports:
      - ${GOGS_WEB_PORT}:3000
      - ${GOGS_SSH_PORT}:22
    volumes:
      - ${GOGS_DATA_DIR}:/data
      - ${GOGS_LOG_DIR}:/app/gogs/log
    depends_on:
      - db
  db:
    env_file: .env
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION:-latest}
    container_name: gogs-mysql
    restart: on-failure
    volumes:
      - ${GOGS_DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-gogs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER:-gogs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
